CORRECT_USERNAME = 'test'
CORRECT_USERNAME_2 = 'test2'
CORRECT_USERNAME_3 = 'test3'

CORRECT_PASSWORD = 'test'
WRONG_PASSWORD = 'wrong password'

CORRECT_FIRST_NAME = 'Test'
CORRECT_LAST_NAME = 'Smith'

CORRECT_EMAIL = 'test@email.com'
CORRECT_EMAIL_2 = 'test2@email.com'
CORRECT_EMAIL_3 = 'test3@email.com'

CORRECT_PHONE = '+79282412233'
CORRECT_PREFIX_URL = 'TEST'

CORRECT_PROJECT_TITLE = 'TEST'
CORRECT_PROJECT_TITLE_2 = 'TEST2'
CORRECT_PROJECT_TITLE_3 = 'TEST CHANGED'

CORRECT_PROJECT_KEY = 'TST'
CORRECT_PROJECT_KEY_2 = 'TST2'
CORRECT_PROJECT_KEY_3 = 'TSTCHD'

CORRECT_ICON_CATEGORY_PREFIX = 'mdi-bookmark'
CORRECT_ICON_CATEGORY_PREFIX_2 = 'mdi-bug'

CORRECT_COLOR = '#f02222'

CORRECT_ISSUE_TYPE_CATEGORY_TITLE = 'User Story'

CORRECT_ISSUE_TITLE = 'As a user i want to create new issue'
CORRECT_ISSUE_DESCRIPTION = 'This description is really good'

CORRECT_ISSUE_MESSAGE_DESCRIPTION = 'Hello, how are you?'

CORRECT_SPRINT_TITLE = 'Crucial Sprint N15'
CORRECT_SPRINT_GOAL = 'Do extremely important things.'

INCORRECT_REFRESH_TOKEN = 'INCORRECT REFRESH_TOKEN'
